const ROOM_STATE_CREATED = 'created';
const ROOM_STATE_STARTED = 'started';
const ROOM_STATE_ENDED = 'ended';
const PLAYER_ROLE_CREATOR = 'creator';
const PLAYER_ROLE_PLAYER = 'player';

const STATUS_ALL_CORRECT = 'correct';
const STATUS_NOT_CORRECT = 'wrong';
const STATUS_PARTIAL_CORRECT = 'partial';
const STATUS_UNKNOWN = 'unknown';

module.exports = {ROOM_STATE_CREATED, ROOM_STATE_ENDED, ROOM_STATE_STARTED, STATUS_PARTIAL_CORRECT, STATUS_ALL_CORRECT, STATUS_NOT_CORRECT, PLAYER_ROLE_CREATOR, PLAYER_ROLE_PLAYER, STATUS_UNKNOWN}
